version: '2.20.2'

services:
  db:
    image: "postgres:15.4-alpine3.18"
    restart: always
    expose:
      - "5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    container_name: postgresdb
    networks:
      - 42_network
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: |
      npm run start:dev
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - "TCD_UID=${TCD_UID}"
      - "TCD_SECRET=${TCD_SECRET}"
      - "TCD_CALLBACKURL=${TCD_CALLBACKURL}"
      - "HOST_NAME=${HOST_NAME}"
    depends_on:
      - db
    networks:
      - 42_network

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    command: |
      npm run start
    container_name: frontend
    ports:
      - "4200:4200"
    environment:
      - "HOST_NAME=${HOST_NAME}"
    depends_on:
      - backend
    networks:
      - 42_network

volumes:
  dbdata:
networks:
  42_network: