version: '2.20.2'

services:
  db:
    image: "postgres:15.4-alpine3.18"
    restart: always
    expose:
      - "5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB:?variable POSTGRES_DB is missing}"
      - "POSTGRES_USER=${POSTGRES_USER:?variable POSTGRES_USER is missing}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?variable POSTGRES_PASSWORD is missing}"
    container_name: postgresdb
    networks:
      - 42_network
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    command: |
      npm run start:prod
    container_name: backend
    expose:
      - "3000"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB:?variable POSTGRES_DB is missing}"
      - "POSTGRES_USER=${POSTGRES_USER:?variable POSTGRES_USER is missing}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?variable POSTGRES_PASSWORD is missing}"
      - "TCD_UID=${TCD_UID:?variable TCD_UID is missing}"
      - "TCD_SECRET=${TCD_SECRET:?variable TCD_SECRET is missing}"
      - "HOST_NAME=${HOST_NAME:?variable HOST_NAME is missing}"
      - "JWT_SECRET=${JWT_SECRET:?variable JWT_SECRET is missing}"
    depends_on:
      - db
    networks:
      - 42_network

  frontend:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
      args:
        HOST_NAME: "${HOST_NAME:?variable HOST_NAME is missing}"
    command: "nginx -g 'daemon off;'"
    container_name: frontend
    ports:
      - "4200:4200"
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - 42_network

volumes:
  dbdata:
networks:
  42_network: