version: '2.20.2'

services:
  db:
    image: "postgres:15.4-alpine3.18"
    restart: always
    ports:
      - "5432:5432"
  #   expose:
  #    - "5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    container_name: postgresdb
    networks:
      - 42_network
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
networks:
  42_network: