import { Channel } from 'src/app/shared/chat/Channel';
import { EChannelMode } from 'src/app/shared/macros/EChannelMode';
import { EUserRole } from 'src/app/shared/macros/EUserRole';

export const dummyChannels: Channel[] = [
    {
        name: '🚀 Channel 1',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🎉 Channel 2',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌟 Channel 3',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🔒 Channel 4',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🎈 Channel 5',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🌴 Channel 6',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🍔 Channel 7',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚁 Channel 8',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌈 Channel 9',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚢 Channel 10',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🏖️ Channel 11',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚗 Channel 12',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🍕 Channel 13',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🌌 Channel 14',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🎃 Channel 15',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍭 Channel 16',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🎇 Channel 17',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚀 Channel 18',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌄 Channel 19',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🌾 Channel 20',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌺 Channel 21',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍦 Channel 22',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🚤 Channel 23',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍩 Channel 24',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🎸 Channel 25',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍺 Channel 26',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌮 Channel 27',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🎯 Channel 28',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🚁 Channel 29',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🏖️ Channel 30',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🚢 Channel 31',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🌅 Channel 32',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌃 Channel 33',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚓 Channel 34',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🚀 Channel 35',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.OWNER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍕 Channel 36',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🌆 Channel 37',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.NONE,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🍎 Channel 38',
        mode: EChannelMode.PROTECTED,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
      {
        name: '🚖 Channel 39',
        mode: EChannelMode.PUBLIC,
        role: EUserRole.ADMIN,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3],
      },
      {
        name: '🚀 Channel 40',
        mode: EChannelMode.PRIVATE,
        role: EUserRole.USER,
        isBanned: false,
        isMuted: false,
        users: [1, 2, 3, 4, 5, 6],
      },
    ]    
